name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List frontend directory contents
        run: ls -l ./frontend

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Backend Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/codevibe/backend:latest ./backend
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/codevibe/backend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy codevibe-backend \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/codevibe/backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 5000 \
            --set-env-vars CLIENT_URL="https://codevibe-frontend-${{ secrets.GCP_PROJECT_ID }}.run.app"

      - name: Build and Push Frontend Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/codevibe/frontend:latest ./frontend
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/codevibe/frontend:latest

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy codevibe-frontend \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/codevibe/frontend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000 \
            --set-env-vars REACT_APP_API_BASE_URL="https://codevibe-backend-${{ secrets.GCP_PROJECT_ID }}.run.app"